In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3], 
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 8, 4, 8, 9],
       [1, 5, 3, 9, 2],
       [3, 4, 9, 2, 0]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.28146228, 0.45592162, 0.59177149],
       [0.89399751, 0.68967183, 0.6549619 ],
       [0.22325518, 0.97434229, 0.30421947],
       [0.05324932, 0.98981804, 0.11500701],
       [0.8843626 , 0.2513751 , 0.51000189]])

In [31]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.61925137, 0.68732136, 0.98479314],
       [0.21348728, 0.65457222, 0.71769033],
       [0.92342473, 0.79995414, 0.79507401],
       [0.21437442, 0.93551336, 0.28247092],
       [0.71623061, 0.9666818 , 0.71715321]])

In [46]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [53]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [54]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [55]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [56]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a1

array([1, 2, 3])

In [58]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [60]:
a1[0]

1

In [62]:
a2.shape

(2, 3)

In [61]:
a2[0]

array([1. , 2. , 3.3])

In [63]:
a3.shape

(2, 3, 3)

In [64]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [67]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [68]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [71]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating & comparing arrays

### Artihmetic

In [72]:
a1

array([1, 2, 3])

In [74]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [75]:
a1 + ones

array([2., 3., 4.])

In [76]:
a1 - ones

array([0., 1., 2.])

In [77]:
a1 * ones

array([1., 2., 3.])

In [80]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [81]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [82]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape NumPy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [83]:
a1 / ones

array([1., 2., 3.])

In [85]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [84]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [86]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [87]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [88]:
np.add(a1, ones)
a1 % 2

array([1, 0, 1])

In [89]:
a1 / 2

array([0.5, 1. , 1.5])

In [90]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [91]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [92]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [93]:
sum(listy_list)

6

In [95]:
sum(a1)

6

In [96]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [97]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [99]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [100]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

4.34 ms ± 151 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.3 μs ± 139 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [101]:
17900 / 34

526.4705882352941

In [102]:
np.mean(a2)

3.6333333333333333

In [103]:
np.max(a2)

6.5

In [104]:
np.min(a2)

1.0

In [105]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [106]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [108]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422